### ISSUE TITLE
Can not disable validation rules for any element

### ISSUE THREAD

**Issue by szabolcsmucsi** [vueform/builder#1]
### Environment

@vueform/vueform 1.54
@vueform/builder 1.1.5
vue 3.3.4
vite 4.4.5

### Reproduction

```js
// builder.config.js

element: {
    props: {
      default: {
        validation: {
          validation: {
            nullable: false
          }
        },
      }
   }
}
```

### Describe the bug

Trying to disable any validation rule will do nothing

**Comment by adamberecz** [comment]
Fixed in `1.1.6`
