### ISSUE TITLE
Radiogroup and checkboxgroup options gets overwritten when clicked after a Select

### ISSUE THREAD

**Issue by jensjns** [vueform/builder#40]
### Environment

@vueform/builder ^1.1.6
@vueform/vueform ^1.6.5

### Reproduction

-

### Describe the bug

1. Have 3 fields: Radiogroup with options, Checkboxgroup with options, Select with options.
2. Click on the Select field.
3. Click on either the Radiogroup or the Checkboxgroup.
4. The options from the Select field will transfer/copy to the clicked field.

<img width="1714" alt="Window_and_Ändra_formuläret_för_Dolor_-_Selfcheck" src="https://github.com/vueform/builder/assets/1078300/c95f8c96-d5da-405d-a30d-d16b03d77545">

**Comment by jensjns** [comment]
After click on the radiogroup the form looks like this:

<img width="1708" alt="Window_and_Ändra_formuläret_för_Dolor_-_Selfcheck" src="https://github.com/vueform/builder/assets/1078300/9e51eb40-8a78-462c-aa13-53ac2682f3f1">

**Comment by adamberecz** [comment]
Thanks for reporting the issue @jensjns - we'll look into it and get back with a fix.

**Comment by jensjns** [comment]
Thanks @adamberecz 👍 These are the fields that I found that is affected by this bug. Might be other fields that supports options that's affected too.

**Comment by adamberecz** [comment]
`1.1.10` is out which should contain a fix. Please let me know if you still encounter any similar issues.

**Comment by jensjns** [comment]
Just upgraded to 1.1.10 and it's fixed 👍 Thanks for the super quick response and fix
