### ISSUE TITLE
HTML field doesn't escape quotes

### ISSUE THREAD

**Issue by letmaik** [vueform/builder#55]
### Environment

https://builder.vueform.com/demo

### Reproduction

Add some HTML in the content field, then switch to Code.

### Describe the bug

![image](https://github.com/vueform/builder/assets/530988/6d8d113c-5d43-4a05-ae2d-40e21fa7a071)

**Comment by adamberecz** [comment]
Thank you for reporting the issue. Fixed in `1.4.0`.
