### ISSUE TITLE
When using AI in the Form Builder, save event does not get called

### ISSUE THREAD

**Issue by TakumiHendricksDev** [vueform/builder#72]
### Environment

Framework
"vite": "^5.2.10",
"vue": "^3.4.25",
Package Manager
npm
Vueform and Builder versions
"builder":"1.4.6"
"vueform":"1.10.1"

### Reproduction

Use the FormBuilder Vue component and use the AI feature to generate a form. The Save event handler does not get called after the AI response gets generated. To have it called, I have to manually add a new field or update one of the fields for the save handler to get called.

### Describe the bug

When using the Form Builder the component should call a save event when the AI returns a form response. Currently this isn't happening and I need to either edit a field for it to call the save event or add a new field.

### Additional context

I didn't add a repo but this should be a fairly simple reproduction.

**Comment by adamberecz** [comment]
Fixed in `1.6.0`
