### ISSUE TITLE
Error on adding Nested List

### ISSUE THREAD

**Issue by dan-dazlab** [vueform/builder#88]
### Environment

1.8.0 release[​](https://builder.vueform.com/releases/1.8.0#_1-8-0-release)
Release date: 2024-10-29

### Reproduction

https://builder.vueform.com/examples/basics-default
Add Nested List from Structure.

### Describe the bug

I cannot add Nested list it's critical base functionality.

### Logs

```shell-script
widget.js:160 Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at index.DArI6QHe.js:126:146260
    at o (widget.js:160:1706)
﻿
```

**Comment by adamberecz** [comment]
Thank you for reporting the issue—a fix is released in `1.8.1`.
