### ISSUE TITLE
Matrix-Element with dynamic rows deletes content if row is added

### ISSUE THREAD

**Issue by everydaysoftware** [vueform/builder#90]
### Environment

Vue 2.7
@vueform/vueform": "^1.11.0

Your Builder environment
Examples in your component description

### Reproduction

https://builder.vueform.com/demo
https://vueform.com/reference/matrix-element

### Describe the bug

Add matrix element with dynamic rows

`vueform: {
      schema: {
        matrix: {
          type: 'matrix',
          cols: [
            {
              label: 'Column 1',
              value: 'column_1',
              inputType: {
                type: 'text',
                inputType: 'number',
                autocomplete: 'off',
                forceNumbers: true,
              },
            },
            {
              label: 'Column 2',
              value: 'column_2',
              inputType: {
                type: 'text',
              },
            },
          ],
          rows: 1,
          presets: [
            'matrix-table',
          ],
        },
      },
    }`

Fill out first row then add new row. 
All values will be deleted.

![vueform-matrix-1](https://github.com/user-attachments/assets/099e493a-f81f-4cb8-9f73-8f0743aab1d8)

![vueform-matrix-2](https://github.com/user-attachments/assets/b236efbf-4f8e-4c2a-b338-64d7e883d6b0)

This also happens in own implementation.

**Comment by adamberecz** [comment]
The issue was in `@vueform/vueform`, which got patched in `1.11.1`. Thanks for reporting the issue.
